version: '3'

services:
  my_tensorflow:
    image: tensorflow/tensorflow
    container_name: my_tensorflow_container
    volumes:
      - ../.:/notebooks
    ports:
      - "8888:8888"
    restart: always